### PR TITLE
overriding bootstrap pagination styles to match toolkit styles

### LINKED ISSUE #884: Swap out bootstrap5 pager with toolkit pager
The bootstrap5 theme's built-in pager needs to be replaced with the Illinois toolkit pager

The bootstrap5 theme has a pager template file at themes/contrib/bootstrap5/templates/navigation/pager.html.twig

A new pager.html.twig template needs to be created in the illinois_framework_theme that uses the Illinois toolkit pager. Documentation can be found at: https://help.toolkit.illinois.edu/component/pagination/

An example of the bootstrap5 pager can be seen at the bottom of the page at https://drupal-sandbox.webtheme.illinois.edu/

image

### PR DESCRIPTION
**Pull request by nhjohnstone**

### CODE REVIEW

**Comment by trubach** [comment]
Closing this PR because we're waiting on the toolkit devs to resolve web-illinois/toolkit#419

**Comment by nhjohnstone** [comment]
@trubach can we reopen this PR for the pagination styles, or do you want me to create a new PR?

**Comment by trubach** [comment]
After looking at the toolkit pager, there's not a clear way to include additional URL parameters, such as "?page=1&keyword=tests". Until we can figure out a way around that, we can match the style of the toolkit.

**Comment by trubach** [comment]
@nhjohnstone - can you double-check that the styles in this PR still work in the latest framework release? If it looks good on your end, I'll go ahead and merge it and we can test it out on the dev site.

**Comment by nhjohnstone** [comment]
@trubach everything looks good on my local.

**Pull request merged**
